version: '3'

services:

  php:
    build: .
    image: php:8.1-apache
    container_name: teste-NT
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    container_name: my-mysql-php
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=db_testeNT
      - MYSQL_USER=thiago
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345

volumes:
  db_data: